@collection=department

### Get all
GET {{host}}/{{collection}}

### GET 1
GET {{host}}/{{collection}}/6037e06cdad2ba45a4d20cf1



### Create

POST {{host}}/{{collection}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "phong hành chính"
}

### Update
PUT {{host}}/{{collection}}/6038c109d70ca15664df3ee8
Content-Type: application/json
Authorization: Bearer {{tokenForever}}

{
    "name": "Phòng nhân sự"
}


### Delete
DELETE {{host}}/{{collection}}/6038b8b20c9f5550587d2d33
Authorization: Bearer {{accessToken}}