
@collection=team
# 6037e06cdad2ba45a4d20cf1

######### 
GET {{host}}/{{collection}}

######### 
GET {{host}}/{{collection}}/6037c5e2c441ca397c2f8835
###


POST {{host}}/{{collection}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "demo",
    "department": "6037e06cdad2ba45a4d20cf1",
    "manager": "6037cb7598ce504e8cc73b2c"
}

###
PUT {{host}}/{{collection}}/6037c5e8c441ca397c2f8837
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "demo234"
}


###
DELETE {{host}}/{{collection}}/6037c5e8c441ca397c2f8837
Authorization: Bearer {{accessToken}}