@collection=user


######### 
GET {{host}}/{{collection}}

######### Get multi with query params
GET {{host}}/{{collection}}?limit=1&page=2&select=lastName,firstName


######### Get 1 with [select] query
GET {{host}}/{{collection}}/60387915e97ecb57680181e7

###


POST {{host}}/{{collection}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "lastName": "Vuong",
    "firstName": "Dang",
    "team": "6037c5e2c441ca397c2f8835",
    "userType": "staff",
    "department": "6038b4c03816df448889bfa9"
}

###
PUT {{host}}/{{collection}}/60387915e97ecb57680181e7
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "lastName": "Vuong",
    "firstName": "Dang",
    "userType": "staff"
}


###
DELETE {{host}}/{{collection}}/603878fed3580e08542a6f97
Authorization: Bearer {{accessToken}}